### ISSUE TITLE
Can not use and install git, vi and other commands

### ISSUE THREAD

**Issue by lonly197** [steveny2k/docker-predictionio#10]
##  Can not use and install git, vi and other commands

Since I need to start the pio engine service, I need to download the pio engine template by using git.
But when I want to install packages such as git, always prompt "Unable to locate package git" such a mistake.

**Comment by steveny2k** [comment]
@lonly197 You can install git inside docker container. 
I can also pre-install git in the image in the future.

You can do below steps once inside the docker container.
sudo apt-get update
sudo apt-get install -y git
