### ISSUE TITLE
first time using it

### ISSUE THREAD

**Issue by juanbits** [steveny2k/docker-predictionio#4]
Hi, this is my first time using predictionio and docker.

I follow the instructions thar are on https://github.com/steveny2k/docker-predictionio/ it was installed and when i execute

```
root@2bf705b53a6b:/PredictionIO-0.10.0-incubating# pio eventserver --port 7071
[INFO] [Console$] Creating Event Server at 0.0.0.0:7071
[INFO] [HttpListener] Bound to /0.0.0.0:7071
[INFO] [EventServerActor] Bound received. EventServer is ready.
```

i cant acces via localhost:7071, cant reach the server and i dont know how can i try this example http://predictionio.incubator.apache.org/templates/similarproduct/quickstart/ because when im inside the docker i cant execute (command not found)
`git clone ...`

actually i dont know where is installed predictionio to do this
`PATH=$PATH:/home/yourname/PredictionIO/bin; export PATH`

i have this outputs too:
```
root@2bf705b53a6b:/PredictionIO-0.10.0-incubating# pio-stop-all
Stopping PredictionIO Event Server...
Stopping HBase...
stopping hbase...................
Stopping Elasticsearch...
/PredictionIO-0.10.0-incubating/bin/pio-stop-all: line 58: sudo: command not found
```

```
root@2bf705b53a6b:/PredictionIO-0.10.0-incubating# pio-start-all
Starting Elasticsearch...
Starting HBase...
starting master, logging to /PredictionIO-0.10.0-incubating/vendors/hbase-1.0.0/bin/../logs/hbase--master-2bf705b53a6b.out
/PredictionIO-0.10.0-incubating/bin/pio-start-all: line 74: sudo: command not found
Waiting 10 seconds for HBase to fully initialize...
Starting PredictionIO Event Server...
```

anyone can help me?
thanks

**Comment by steveny2k** [comment]
@juanremi 
Could you try?
$ docker run -it -p 8000:8000 steveny/predictionio:0.12.0 /bin/bash
then
$ pio-start-all
thanks for feedback.

**Comment by steveny2k** [comment]
@juanremi 
Thanks for reporting the issue. The issue has been resolved and you can take a look at the details at https://github.com/steveny2k/docker-predictionio/issues/5 ? 
I am closing this issue to consolidate. Thanks again

**Comment by steveny2k** [comment]
@juanremi 
You can install git inside the container and then can clone.
You can also ignore `/PredictionIO-0.10.0-incubating/bin/pio-start-all: line 74: sudo: command not found`, since that line is for postgres, and this docker image does not install postgres. If you need, you can install postgres manually.
