### ISSUE TITLE
PIO BUILD error

### ISSUE THREAD

**Issue by farhanhu87** [steveny2k/docker-predictionio#6]
Hi,
Hope you doing well,
When i run command "pio build" it giving me below error.
![image](https://user-images.githubusercontent.com/3365322/34352287-73b1b644-ea43-11e7-9b3f-9a46de00da12.png)

Please help.
@steveny2k

**Comment by steveny2k** [comment]
it is discussed in https://github.com/steveny2k/docker-predictionio/issues/5
